-- Team-level merit and demerit adjustments for Manage Teams.
-- Run this in the Supabase SQL Editor for the dashboard project.

create table if not exists public.team_point_adjustments (
    id bigint generated by default as identity primary key,
    team_id bigint references public.sports_leaderboard(id) on delete cascade,
    team text not null,
    adjustment_type text not null check (adjustment_type in ('merit', 'demerit')),
    points numeric not null check (points > 0),
    remarks text not null check (length(btrim(remarks)) > 0),
    created_by text,
    created_by_name text,
    created_at timestamptz not null default now()
);

create index if not exists team_point_adjustments_team_id_idx
on public.team_point_adjustments (team_id);

create index if not exists team_point_adjustments_team_idx
on public.team_point_adjustments (lower(team));

alter table public.team_point_adjustments enable row level security;

grant select on public.team_point_adjustments to anon, authenticated;
grant insert on public.team_point_adjustments to authenticated;

drop policy if exists "Anyone can read team point adjustments" on public.team_point_adjustments;
create policy "Anyone can read team point adjustments"
on public.team_point_adjustments
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can add team point adjustments" on public.team_point_adjustments;
create policy "Admins can add team point adjustments"
on public.team_point_adjustments
for insert
to authenticated
with check (public.app_is_admin());

do $$
begin
    alter publication supabase_realtime add table public.team_point_adjustments;
exception
    when duplicate_object then null;
    when undefined_object then null;
end $$;
