-- Locked attendance point logs from August 16, 2026 onward.
-- Run this in Supabase SQL Editor. It leaves attendance before 2026-08-16 untouched.

create table if not exists public.attendance_point_logs (
    id bigint generated by default as identity primary key,
    attendance_date date not null,
    session_title text not null,
    team text not null,
    total_present integer not null default 0,
    registered_player_count integer not null default 0,
    student_player_count integer not null default 0,
    faculty_count integer not null default 0,
    department_chair_count integer not null default 0,
    dean_count integer not null default 0,
    student_from_college_count integer not null default 0,
    sponsor_count integer not null default 0,
    sponsor_game_attendance_count integer not null default 0,
    total_students numeric not null default 0,
    total_faculty numeric not null default 0,
    total_department_chairs numeric not null default 0,
    registered_player_points numeric not null default 5,
    student_player_points numeric not null default 0,
    faculty_points numeric not null default 5,
    department_chair_points numeric not null default 100,
    dean_points numeric not null default 50,
    sponsor_points numeric not null default 5,
    sponsor_game_attendance_points numeric not null default 15,
    total_points numeric not null default 0,
    point_settings jsonb not null default '{}'::jsonb,
    locked_at timestamptz not null default now(),
    source text not null default 'refresh_attendance_point_log'
);

alter table public.attendance_point_logs
    add column if not exists attendance_date date,
    add column if not exists session_title text,
    add column if not exists team text,
    add column if not exists total_present integer not null default 0,
    add column if not exists registered_player_count integer not null default 0,
    add column if not exists student_player_count integer not null default 0,
    add column if not exists faculty_count integer not null default 0,
    add column if not exists department_chair_count integer not null default 0,
    add column if not exists dean_count integer not null default 0,
    add column if not exists student_from_college_count integer not null default 0,
    add column if not exists sponsor_count integer not null default 0,
    add column if not exists sponsor_game_attendance_count integer not null default 0,
    add column if not exists total_students numeric not null default 0,
    add column if not exists total_faculty numeric not null default 0,
    add column if not exists total_department_chairs numeric not null default 0,
    add column if not exists registered_player_points numeric not null default 5,
    add column if not exists student_player_points numeric not null default 0,
    add column if not exists faculty_points numeric not null default 5,
    add column if not exists department_chair_points numeric not null default 100,
    add column if not exists dean_points numeric not null default 50,
    add column if not exists sponsor_points numeric not null default 5,
    add column if not exists sponsor_game_attendance_points numeric not null default 15,
    add column if not exists total_points numeric not null default 0,
    add column if not exists point_settings jsonb not null default '{}'::jsonb,
    add column if not exists locked_at timestamptz not null default now(),
    add column if not exists source text not null default 'refresh_attendance_point_log';

create index if not exists attendance_point_logs_date_session_team_idx
on public.attendance_point_logs (attendance_date, session_title, team);

alter table public.attendance_sessions
    add column if not exists point_settings jsonb;

create or replace function public.refresh_attendance_point_log(
    p_attendance_date date,
    p_session_title text
)
returns boolean
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
    cutoff_date constant date := date '2026-08-16';
    normalized_session_title text := nullif(trim(coalesce(p_session_title, '')), '');
    selected_point_settings jsonb;
begin
    if p_attendance_date is null or normalized_session_title is null then
        return false;
    end if;

    if p_attendance_date < cutoff_date then
        return false;
    end if;

    select coalesce(
        (
            select session_row.point_settings
            from public.attendance_sessions session_row
            where session_row.attendance_date = p_attendance_date
              and lower(trim(session_row.category)) = lower(normalized_session_title)
            order by session_row.updated_at desc nulls last, session_row.id desc
            limit 1
        ),
        (
            select attendance_row.attendance_point_settings
            from public.attendance attendance_row
            where attendance_row.attendance_date = p_attendance_date
              and lower(trim(coalesce(attendance_row.attendance_session_title, ''))) = lower(normalized_session_title)
              and attendance_row.attendance_point_settings is not null
            order by attendance_row.checked_at desc nulls last, attendance_row.id desc
            limit 1
        ),
        (
            select settings.point_settings
            from public.attendance_settings settings
            where settings.id = 1
            limit 1
        ),
        '{}'::jsonb
    )
    into selected_point_settings;

    delete from public.attendance_point_logs
    where attendance_date = p_attendance_date
      and lower(trim(coalesce(session_title, ''))) = lower(normalized_session_title);

    insert into public.attendance_point_logs (
        attendance_date,
        session_title,
        team,
        total_present,
        registered_player_count,
        student_player_count,
        faculty_count,
        department_chair_count,
        dean_count,
        student_from_college_count,
        sponsor_count,
        sponsor_game_attendance_count,
        total_students,
        total_faculty,
        total_department_chairs,
        registered_player_points,
        student_player_points,
        faculty_points,
        department_chair_points,
        dean_points,
        sponsor_points,
        sponsor_game_attendance_points,
        total_points,
        point_settings,
        locked_at,
        source
    )
    with safe_parameters as (
        select
            case
                when coalesce(selected_point_settings #>> '{parameters,registered_player_points}', '') ~ '^\d+(\.\d+)?$'
                 and (selected_point_settings #>> '{parameters,registered_player_points}')::numeric between 0 and 1000
                    then (selected_point_settings #>> '{parameters,registered_player_points}')::numeric
                else 5
            end as registered_player_points,
            case
                when coalesce(selected_point_settings #>> '{parameters,student_player_points}', selected_point_settings #>> '{parameters,student_from_college_points}', '') ~ '^\d+(\.\d+)?$'
                 and coalesce(selected_point_settings #>> '{parameters,student_player_points}', selected_point_settings #>> '{parameters,student_from_college_points}')::numeric between 0 and 1000
                    then coalesce(selected_point_settings #>> '{parameters,student_player_points}', selected_point_settings #>> '{parameters,student_from_college_points}')::numeric
                else 0
            end as student_player_points,
            case
                when coalesce(selected_point_settings #>> '{parameters,faculty_points}', '') ~ '^\d+(\.\d+)?$'
                 and (selected_point_settings #>> '{parameters,faculty_points}')::numeric between 0 and 1000
                    then (selected_point_settings #>> '{parameters,faculty_points}')::numeric
                else 5
            end as faculty_points,
            case
                when coalesce(selected_point_settings #>> '{parameters,department_chair_formula_base}', '') ~ '^\d+(\.\d+)?$'
                 and (selected_point_settings #>> '{parameters,department_chair_formula_base}')::numeric between 0 and 1000
                    then (selected_point_settings #>> '{parameters,department_chair_formula_base}')::numeric
                else 100
            end as department_chair_points,
            case
                when coalesce(selected_point_settings #>> '{parameters,dean_points}', '') ~ '^\d+(\.\d+)?$'
                 and (selected_point_settings #>> '{parameters,dean_points}')::numeric between 0 and 1000
                    then (selected_point_settings #>> '{parameters,dean_points}')::numeric
                else 50
            end as dean_points,
            case
                when coalesce(selected_point_settings #>> '{parameters,sponsor_points}', '') ~ '^\d+(\.\d+)?$'
                 and (selected_point_settings #>> '{parameters,sponsor_points}')::numeric between 0 and 1000
                    then (selected_point_settings #>> '{parameters,sponsor_points}')::numeric
                else 5
            end as sponsor_points,
            case
                when coalesce(selected_point_settings #>> '{parameters,sponsor_game_attendance_points}', '') ~ '^\d+(\.\d+)?$'
                 and (selected_point_settings #>> '{parameters,sponsor_game_attendance_points}')::numeric between 0 and 1000
                    then (selected_point_settings #>> '{parameters,sponsor_game_attendance_points}')::numeric
                else 15
            end as sponsor_game_attendance_points,
            coalesce(
                selected_point_settings #> '{parameters,college_totals}',
                selected_point_settings #> '{opening_program,college_totals}',
                '{}'::jsonb
            ) as college_totals
    ),
    normalized_attendance as (
        select
            attendance_row.id,
            attendance_row.attendance_date,
            coalesce(nullif(trim(attendance_row.attendance_session_title), ''), 'Attendance') as session_title,
            case
                when coalesce(attendance_row.attendance_category, '') in (
                    'registered_player',
                    'student_player',
                    'faculty',
                    'department_chair',
                    'dean',
                    'student_from_college',
                    'sponsor',
                    'sponsor_game_attendance'
                ) then attendance_row.attendance_category
                when attendance_row.participant_id is not null
                 and lower(coalesce(participant.status, '')) = 'approved'
                    then 'registered_player'
                else 'student_player'
            end as resolved_attendance_category,
            coalesce(attendance_row.status, 'Present') as attendance_status,
            case btrim(lower(regexp_replace(coalesce(
                case
                    when attendance_row.participant_id is not null and nullif(participant.team, '') is not null then participant.team
                    else null
                end,
                nullif(attendance_row.home_college, ''),
                nullif(attendance_row.team, '')
            ), '[^a-zA-Z0-9]+', ' ', 'g')))
                when 'college of science engineering and technology' then 'CSET'
                when 'college of nursing' then 'CON'
                when 'college of business' then 'COB'
                when 'college of arts and humanities' then 'CAH'
                when 'college of theology' then 'COT'
                when 'college of health' then 'COH'
                when 'college of medicine' then 'COM'
                when 'college of teacher education' then 'CTE'
                when 'college of teachers education' then 'CTE'
                when 'college of dentistry' then 'COD'
                when 'academy' then 'Academy'
                when 'faculty' then 'Faculty'
                else upper(btrim(coalesce(
                    case
                        when attendance_row.participant_id is not null and nullif(participant.team, '') is not null then participant.team
                        else null
                    end,
                    nullif(attendance_row.home_college, ''),
                    nullif(attendance_row.team, '')
                )))
            end as team
        from public.attendance attendance_row
        left join public.participants participant
            on participant.id::text = attendance_row.participant_id::text
        where attendance_row.attendance_date = p_attendance_date
          and lower(trim(coalesce(attendance_row.attendance_session_title, ''))) = lower(normalized_session_title)
    ),
    attendance_counts as (
        select
            normalized_attendance.attendance_date,
            normalized_attendance.session_title,
            normalized_attendance.team,
            count(*) as total_present,
            count(*) filter (where normalized_attendance.resolved_attendance_category = 'registered_player') as registered_player_count,
            count(*) filter (where normalized_attendance.resolved_attendance_category in ('student_player', 'student_from_college')) as student_player_count,
            count(*) filter (where normalized_attendance.resolved_attendance_category = 'faculty') as faculty_count,
            count(*) filter (where normalized_attendance.resolved_attendance_category = 'department_chair') as department_chair_count,
            count(*) filter (where normalized_attendance.resolved_attendance_category = 'dean') as dean_count,
            count(*) filter (where normalized_attendance.resolved_attendance_category in ('student_player', 'student_from_college')) as student_from_college_count,
            count(*) filter (where normalized_attendance.resolved_attendance_category = 'sponsor') as sponsor_count,
            count(*) filter (where normalized_attendance.resolved_attendance_category = 'sponsor_game_attendance') as sponsor_game_attendance_count
        from normalized_attendance
        where lower(coalesce(normalized_attendance.attendance_status, 'present')) = 'present'
          and normalized_attendance.team in ('CAH', 'COB', 'COD', 'COH', 'COM', 'CON', 'COT', 'CSET', 'CTE', 'Academy', 'Faculty')
        group by normalized_attendance.attendance_date, normalized_attendance.session_title, normalized_attendance.team
    ),
    scored_attendance as (
        select
            attendance_counts.*,
            coalesce(college_totals.total_students, 0) as total_students,
            coalesce(college_totals.total_faculty, 0) as total_faculty,
            coalesce(college_totals.total_department_chairs, 0) as total_department_chairs,
            safe_parameters.registered_player_points,
            safe_parameters.student_player_points,
            safe_parameters.faculty_points,
            safe_parameters.department_chair_points,
            safe_parameters.dean_points,
            safe_parameters.sponsor_points,
            safe_parameters.sponsor_game_attendance_points,
            round((
                (attendance_counts.registered_player_count * safe_parameters.registered_player_points)
                + case
                    when coalesce(college_totals.total_students, 0) > 0
                        then ((attendance_counts.student_player_count::numeric / nullif(college_totals.total_students, 0)) * 100) * safe_parameters.student_player_points
                    else 0
                end
                + case
                    when coalesce(college_totals.total_faculty, 0) > 0
                        then ((attendance_counts.faculty_count::numeric / nullif(college_totals.total_faculty, 0)) * 100) * safe_parameters.faculty_points
                    else 0
                end
                + case
                    when coalesce(college_totals.total_department_chairs, 0) > 0
                        then ((attendance_counts.department_chair_count::numeric / nullif(college_totals.total_department_chairs, 0)) * 100) * safe_parameters.department_chair_points
                    else 0
                end
                + (attendance_counts.dean_count * safe_parameters.dean_points)
                + (attendance_counts.sponsor_count * safe_parameters.sponsor_points)
                + (attendance_counts.sponsor_game_attendance_count * safe_parameters.sponsor_game_attendance_points)
            ), 2) as total_points
        from attendance_counts
        cross join safe_parameters
        left join lateral (
            select
                case
                    when coalesce(value ->> 'total_students', value ->> 'total_student_players', '') ~ '^\d+(\.\d+)?$'
                        then least(coalesce(value ->> 'total_students', value ->> 'total_student_players')::numeric, 10000)
                    else 0
                end as total_students,
                case
                    when coalesce(value ->> 'total_faculty', '') ~ '^\d+(\.\d+)?$'
                        then least((value ->> 'total_faculty')::numeric, 10000)
                    else 0
                end as total_faculty,
                case
                    when coalesce(value ->> 'total_department_chairs', '') ~ '^\d+(\.\d+)?$'
                        then least((value ->> 'total_department_chairs')::numeric, 10000)
                    else 0
                end as total_department_chairs
            from jsonb_each(coalesce(safe_parameters.college_totals, '{}'::jsonb))
            where lower(key) = lower(attendance_counts.team)
               or lower(value ->> 'college_name') = lower(attendance_counts.team)
            limit 1
        ) college_totals on true
    )
    select
        scored_attendance.attendance_date,
        scored_attendance.session_title,
        scored_attendance.team,
        scored_attendance.total_present,
        scored_attendance.registered_player_count,
        scored_attendance.student_player_count,
        scored_attendance.faculty_count,
        scored_attendance.department_chair_count,
        scored_attendance.dean_count,
        scored_attendance.student_from_college_count,
        scored_attendance.sponsor_count,
        scored_attendance.sponsor_game_attendance_count,
        scored_attendance.total_students,
        scored_attendance.total_faculty,
        scored_attendance.total_department_chairs,
        scored_attendance.registered_player_points,
        scored_attendance.student_player_points,
        scored_attendance.faculty_points,
        scored_attendance.department_chair_points,
        scored_attendance.dean_points,
        scored_attendance.sponsor_points,
        scored_attendance.sponsor_game_attendance_points,
        scored_attendance.total_points,
        selected_point_settings,
        now(),
        'refresh_attendance_point_log'
    from scored_attendance;

    return true;
end
$$;

revoke all on function public.refresh_attendance_point_log(date, text) from public;
grant execute on function public.refresh_attendance_point_log(date, text) to authenticated;
grant select on public.attendance_point_logs to anon, authenticated;
