-- Fresh-school bootstrap for the CSC L.I.V.E. web application.
-- Run once in a NEW Supabase project's SQL Editor.
-- This creates an empty application database. It does not copy CSC data.
--
-- After running this file:
-- 1. Update SUPABASE_URL and SUPABASE_ANON_KEY in index.html,
--    AdminDashboard.html, CommitteeDashboard.html, and StudentDashboard.html.
-- 2. Register the first admin through index.html.
-- 3. Promote that first admin in the SQL Editor with:
--      update public.user_profiles
--      set approval_status = 'approved'
--      where lower(email) = lower('FIRST_ADMIN_EMAIL');
-- 4. Create teams and sports from the admin dashboard.

begin;

create extension if not exists pgcrypto;

-- Core tournament tables ----------------------------------------------------

create table if not exists public.sports (
    id bigint generated by default as identity primary key,
    sport_name text not null unique,
    points_per_game numeric(12, 2) not null default 0 check (points_per_game >= 0),
    winner_points numeric(12, 2) not null default 0 check (winner_points >= 0),
    loser_points numeric(12, 2) not null default 0 check (loser_points >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.sports_leaderboard (
    id bigint generated by default as identity primary key,
    team text not null unique,
    points numeric(12, 2) not null default 0,
    wins integer not null default 0,
    losses integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.participants (
    id bigint generated by default as identity primary key,
    name text not null,
    student_id text not null unique,
    team text not null,
    status text not null default 'Pending'
        check (status in ('Approved', 'Pending', 'Rejected')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    participant_id bigint references public.participants(id) on delete set null,
    student_id text not null,
    participant_name text not null default '',
    team text not null default '',
    status text not null default 'Present',
    attendance_date date not null default current_date,
    checked_at timestamptz not null default now(),
    unique (student_id, attendance_date)
);

create table if not exists public.scheduled_matches (
    id bigint generated by default as identity primary key,
    sport_id bigint not null references public.sports(id),
    team_one_id bigint not null references public.sports_leaderboard(id),
    team_two_id bigint not null references public.sports_leaderboard(id),
    match_time timestamptz not null,
    location text not null default '',
    status text not null default 'Next'
        check (status in ('Next', 'Ongoing', 'Done')),
    match_stage text not null default 'regular'
        check (match_stage in ('regular', 'semifinals', 'finals', 'battle_for_third')),
    game_period integer check (game_period is null or game_period between 1 and 5),
    timer_enabled boolean not null default false,
    timer_duration_seconds integer not null default 600
        check (timer_duration_seconds >= 0),
    timer_started_at timestamptz,
    created_by text not null,
    created_by_role text not null default 'committee',
    created_by_name text not null default '',
    delete_requested boolean not null default false,
    delete_requested_at timestamptz,
    delete_requested_by text,
    delete_requested_by_name text,
    delete_approved boolean not null default false,
    delete_approved_at timestamptz,
    delete_approved_by text,
    delete_rejected boolean not null default false,
    delete_rejected_at timestamptz,
    delete_rejected_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (team_one_id <> team_two_id)
);

create table if not exists public.game_history (
    id bigint generated by default as identity primary key,
    match_id bigint not null unique references public.scheduled_matches(id) on delete cascade,
    sport_id bigint references public.sports(id) on delete set null,
    sport_name text,
    team_one_id bigint references public.sports_leaderboard(id) on delete set null,
    team_two_id bigint references public.sports_leaderboard(id) on delete set null,
    team_one_name text,
    team_two_name text,
    winner_team_id bigint references public.sports_leaderboard(id) on delete set null,
    winner_team_name text,
    loser_team_id bigint references public.sports_leaderboard(id) on delete set null,
    loser_team_name text,
    winner_points_awarded numeric(12, 2) not null default 0,
    loser_points_awarded numeric(12, 2) not null default 0,
    best_player text,
    match_time timestamptz,
    location text not null default '',
    result text,
    declared_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Public notices and student feedback --------------------------------------

create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    title text not null,
    message text not null,
    audience text not null default 'all'
        check (audience in ('all', 'students', 'committee')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.student_feedback (
    id bigint generated by default as identity primary key,
    feedback_type text not null
        check (lower(trim(feedback_type)) in ('recommendation', 'concern')),
    student_name text,
    student_id text,
    contact_info text,
    message text not null,
    status text not null default 'New'
        check (status in ('New', 'Reviewed')),
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Dashboard accounts and messaging ----------------------------------------

create table if not exists public.user_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null unique,
    full_name text not null,
    mobile_number text not null default '',
    role text not null check (lower(trim(role)) in ('admin', 'committee')),
    approval_status text not null default 'pending'
        check (lower(trim(approval_status)) in ('pending', 'approved', 'hold', 'suspended', 'rejected')),
    assigned_sport_id bigint references public.sports(id) on delete set null,
    assigned_sport_name text,
    reviewed_at timestamptz,
    reviewed_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
    id uuid primary key default gen_random_uuid(),
    created_by uuid not null references auth.users(id) on delete cascade,
    receiver_id uuid not null references auth.users(id) on delete cascade,
    sender_role text not null check (lower(trim(sender_role)) in ('admin', 'committee')),
    receiver_role text not null check (lower(trim(receiver_role)) in ('admin', 'committee')),
    status text not null default 'open',
    last_message text,
    last_message_at timestamptz,
    unread_count_sender integer not null default 0,
    unread_count_receiver integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (created_by <> receiver_id)
);

create table if not exists public.messages (
    id uuid primary key default gen_random_uuid(),
    conversation_id uuid not null references public.conversations(id) on delete cascade,
    sender_id uuid not null references auth.users(id) on delete cascade,
    sender_role text not null check (lower(trim(sender_role)) in ('admin', 'committee')),
    receiver_id uuid not null references auth.users(id) on delete cascade,
    receiver_role text not null check (lower(trim(receiver_role)) in ('admin', 'committee')),
    message_text text,
    attachment_url text,
    attachment_path text,
    is_read boolean not null default false,
    created_at timestamptz not null default now(),
    check (length(trim(coalesce(message_text, ''))) > 0 or attachment_url is not null)
);

create table if not exists public.conversation_user_settings (
    conversation_id uuid not null references public.conversations(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    hidden_at timestamptz,
    primary key (conversation_id, user_id)
);

create index if not exists scheduled_matches_status_time_idx
on public.scheduled_matches (status, match_time);
create index if not exists game_history_declared_at_idx
on public.game_history (declared_at desc);
create index if not exists attendance_date_idx
on public.attendance (attendance_date, checked_at desc);
create index if not exists conversations_users_idx
on public.conversations (created_by, receiver_id, last_message_at desc);
create index if not exists messages_conversation_created_idx
on public.messages (conversation_id, created_at);

-- General timestamp triggers ------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end
$$;

create or replace function public.sync_sport_winner_points()
returns trigger
language plpgsql
as $$
begin
    new.winner_points := new.points_per_game;
    return new;
end
$$;

drop trigger if exists sync_sport_winner_points on public.sports;
create trigger sync_sport_winner_points
before insert or update of points_per_game on public.sports
for each row execute function public.sync_sport_winner_points();

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'sports',
        'sports_leaderboard',
        'participants',
        'scheduled_matches',
        'game_history',
        'announcements',
        'student_feedback',
        'user_profiles',
        'conversations'
    ]
    loop
        execute format('drop trigger if exists set_updated_at on public.%I', table_name);
        execute format(
            'create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
            table_name
        );
    end loop;
end
$$;

create or replace function public.update_conversation_after_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.conversations
    set
        last_message = coalesce(new.message_text, case when new.attachment_url is not null then 'Photo' else '' end),
        last_message_at = new.created_at,
        unread_count_sender = case
            when new.receiver_id = created_by then unread_count_sender + 1
            else unread_count_sender
        end,
        unread_count_receiver = case
            when new.receiver_id = receiver_id then unread_count_receiver + 1
            else unread_count_receiver
        end
    where id = new.conversation_id;

    return new;
end
$$;

drop trigger if exists update_conversation_after_message on public.messages;
create trigger update_conversation_after_message
after insert on public.messages
for each row execute function public.update_conversation_after_message();

-- Authorization helpers -----------------------------------------------------

create or replace function public.app_profile_role(user_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
    select lower(trim(coalesce(role, '')))
    from public.user_profiles
    where id = user_id
    limit 1
$$;

create or replace function public.app_profile_is_approved(user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(lower(trim(approval_status)) = 'approved', false)
    from public.user_profiles
    where id = user_id
    limit 1
$$;

create or replace function public.app_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        public.app_profile_role(auth.uid()) = 'admin'
        and public.app_profile_is_approved(auth.uid()),
        false
    )
$$;

create or replace function public.app_is_dashboard_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        public.app_profile_role(auth.uid()) in ('admin', 'committee')
        and public.app_profile_is_approved(auth.uid()),
        false
    )
$$;

create or replace function public.app_can_read_conversation(conversation_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.conversations conversation_record
        where conversation_record.id = conversation_uuid
          and auth.uid() in (conversation_record.created_by, conversation_record.receiver_id)
    )
$$;

create or replace function public.app_can_send_conversation_message(
    conversation_uuid uuid,
    message_receiver uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.conversations conversation_record
        where conversation_record.id = conversation_uuid
          and (
              (auth.uid() = conversation_record.created_by and message_receiver = conversation_record.receiver_id)
              or
              (auth.uid() = conversation_record.receiver_id and message_receiver = conversation_record.created_by)
          )
    )
$$;

-- Controlled RPC workflows --------------------------------------------------

create or replace function public.save_pending_user_profile(
    p_email text,
    p_full_name text,
    p_mobile_number text,
    p_role text,
    p_assigned_sport_id jsonb default null,
    p_assigned_sport_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
    current_user_id uuid := auth.uid();
    normalized_role text := lower(trim(coalesce(p_role, '')));
    authenticated_email text := lower(trim(coalesce(auth.jwt() ->> 'email', '')));
    resolved_sport_id bigint;
    resolved_sport_name text := nullif(trim(coalesce(p_assigned_sport_name, '')), '');
begin
    if current_user_id is null then
        raise exception 'You must be logged in to create a profile.';
    end if;

    if normalized_role not in ('admin', 'committee') then
        raise exception 'Invalid dashboard role.';
    end if;

    if authenticated_email = ''
       or authenticated_email <> lower(trim(coalesce(p_email, ''))) then
        raise exception 'The authenticated email does not match the registered account.';
    end if;

    if p_assigned_sport_id is not null and p_assigned_sport_id <> 'null'::jsonb then
        resolved_sport_id := trim(both '"' from p_assigned_sport_id::text)::bigint;
    end if;

    if normalized_role = 'committee' and resolved_sport_id is null and resolved_sport_name is null then
        raise exception 'Committee accounts must choose a sport assignment.';
    end if;

    if normalized_role = 'committee' and lower(coalesce(resolved_sport_name, '')) = 'overall committee' then
        raise exception 'Overall Committee access can only be assigned by an admin.';
    end if;

    insert into public.user_profiles (
        id, email, full_name, mobile_number, role, approval_status,
        reviewed_at, reviewed_by, assigned_sport_id, assigned_sport_name
    )
    values (
        current_user_id, trim(p_email), trim(p_full_name), trim(p_mobile_number),
        normalized_role, 'pending', null, null, resolved_sport_id, resolved_sport_name
    )
    on conflict (id)
    do update set
        email = excluded.email,
        full_name = excluded.full_name,
        mobile_number = excluded.mobile_number,
        role = excluded.role,
        assigned_sport_id = excluded.assigned_sport_id,
        assigned_sport_name = excluded.assigned_sport_name
    where lower(trim(public.user_profiles.approval_status)) = 'pending';

    return current_user_id;
end
$$;

create or replace function public.admin_set_account_approval_status(
    target_user_id uuid,
    next_status text
)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
    normalized_status text := lower(trim(coalesce(next_status, '')));
begin
    if not public.app_is_admin() then
        raise exception 'Only an approved admin can update account approvals.';
    end if;

    if target_user_id = auth.uid() then
        raise exception 'You cannot change the approval status of the account currently signed in.';
    end if;

    if normalized_status not in ('approved', 'hold', 'suspended') then
        raise exception 'Invalid account approval status.';
    end if;

    update public.user_profiles
    set approval_status = normalized_status, reviewed_at = now(), reviewed_by = auth.uid()
    where id = target_user_id;

    if not found then
        raise exception 'Account profile not found.';
    end if;
end
$$;

create or replace function public.admin_assign_account_sport(
    target_user_id uuid,
    assigned_sport_id jsonb,
    assigned_sport_name text
)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
    resolved_sport_id bigint;
begin
    if not public.app_is_admin() then
        raise exception 'Only an approved admin can assign account sports.';
    end if;

    if assigned_sport_id is not null and assigned_sport_id <> 'null'::jsonb then
        resolved_sport_id := trim(both '"' from assigned_sport_id::text)::bigint;
    end if;

    update public.user_profiles
    set
        assigned_sport_id = resolved_sport_id,
        assigned_sport_name = nullif(trim(coalesce(assigned_sport_name, '')), '')
    where id = target_user_id;

    if not found then
        raise exception 'Account profile not found.';
    end if;
end
$$;

create or replace function public.set_conversation_visibility(
    p_conversation_ids uuid[],
    p_hidden boolean
)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
    current_user_id uuid := auth.uid();
begin
    if current_user_id is null then
        raise exception 'You must be logged in to update conversation visibility.';
    end if;

    insert into public.conversation_user_settings (conversation_id, user_id, hidden_at)
    select
        conversation_record.id,
        current_user_id,
        case when p_hidden then now() else null end
    from public.conversations conversation_record
    where conversation_record.id = any(coalesce(p_conversation_ids, '{}'::uuid[]))
      and current_user_id in (conversation_record.created_by, conversation_record.receiver_id)
    on conflict (conversation_id, user_id)
    do update set hidden_at = excluded.hidden_at;
end
$$;

create or replace function public.send_conversation_message(
    p_conversation_id uuid,
    p_receiver_id uuid,
    p_message_text text default null,
    p_attachment_url text default null,
    p_attachment_path text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
    current_user_id uuid := auth.uid();
    conversation_record public.conversations%rowtype;
    resolved_sender_role text;
    resolved_receiver_role text;
    inserted_message_id uuid;
begin
    if current_user_id is null then
        raise exception 'You must be logged in to send a message.';
    end if;

    select * into conversation_record
    from public.conversations
    where id = p_conversation_id;

    if not found then
        raise exception 'Conversation not found.';
    end if;

    if current_user_id = conversation_record.created_by
       and p_receiver_id = conversation_record.receiver_id then
        resolved_sender_role := lower(trim(conversation_record.sender_role));
        resolved_receiver_role := lower(trim(conversation_record.receiver_role));
    elsif current_user_id = conversation_record.receiver_id
       and p_receiver_id = conversation_record.created_by then
        resolved_sender_role := lower(trim(conversation_record.receiver_role));
        resolved_receiver_role := lower(trim(conversation_record.sender_role));
    else
        raise exception 'You are not allowed to send a message in this conversation.';
    end if;

    if resolved_sender_role not in ('admin', 'committee')
       or resolved_receiver_role not in ('admin', 'committee') then
        raise exception 'Conversation roles are invalid.';
    end if;

    if length(trim(coalesce(p_message_text, ''))) = 0 and p_attachment_url is null then
        raise exception 'Enter a message or attach a photo.';
    end if;

    insert into public.messages (
        conversation_id, sender_id, sender_role, receiver_id, receiver_role,
        message_text, attachment_url, attachment_path
    )
    values (
        p_conversation_id, current_user_id, resolved_sender_role, p_receiver_id,
        resolved_receiver_role, nullif(trim(coalesce(p_message_text, '')), ''),
        p_attachment_url, p_attachment_path
    )
    returning id into inserted_message_id;

    insert into public.conversation_user_settings (conversation_id, user_id, hidden_at)
    values
        (p_conversation_id, current_user_id, null),
        (p_conversation_id, p_receiver_id, null)
    on conflict (conversation_id, user_id)
    do update set hidden_at = null;

    return inserted_message_id;
end
$$;

create or replace function public.delete_user_account(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
set row_security = off
as $$
begin
    if not public.app_is_admin() then
        raise exception 'Only an approved admin can delete accounts.';
    end if;

    if target_user_id = auth.uid() then
        raise exception 'You cannot delete the account currently signed in.';
    end if;

    delete from auth.users where id = target_user_id;
end
$$;

-- Row-level security --------------------------------------------------------

alter table public.sports enable row level security;
alter table public.sports_leaderboard enable row level security;
alter table public.participants enable row level security;
alter table public.attendance enable row level security;
alter table public.scheduled_matches enable row level security;
alter table public.game_history enable row level security;
alter table public.announcements enable row level security;
alter table public.student_feedback enable row level security;
alter table public.user_profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.conversation_user_settings enable row level security;

create policy "Public can read sports"
on public.sports for select to anon, authenticated using (true);
create policy "Admins can manage sports"
on public.sports for all to authenticated using (public.app_is_admin()) with check (public.app_is_admin());

create policy "Public can read teams"
on public.sports_leaderboard for select to anon, authenticated using (true);
create policy "Admins can manage teams"
on public.sports_leaderboard for all to authenticated using (public.app_is_admin()) with check (public.app_is_admin());

create policy "Public can read participants"
on public.participants for select to anon, authenticated using (true);
create policy "Admins can manage participants"
on public.participants for all to authenticated using (public.app_is_admin()) with check (public.app_is_admin());

create policy "Dashboard users can read attendance"
on public.attendance for select to authenticated using (public.app_is_dashboard_user());
create policy "Dashboard users can create attendance"
on public.attendance for insert to authenticated with check (public.app_is_dashboard_user());
create policy "Dashboard users can update attendance"
on public.attendance for update to authenticated using (public.app_is_dashboard_user()) with check (public.app_is_dashboard_user());
create policy "Admins can delete attendance"
on public.attendance for delete to authenticated using (public.app_is_admin());

create policy "Public can read scheduled matches"
on public.scheduled_matches for select to anon, authenticated using (true);
create policy "Dashboard users can create matches"
on public.scheduled_matches for insert to authenticated
with check (
    public.app_is_dashboard_user()
    and (public.app_is_admin() or created_by = auth.uid()::text)
);
create policy "Admins can update all matches"
on public.scheduled_matches for update to authenticated
using (public.app_is_admin()) with check (public.app_is_admin());
create policy "Committee can update own matches"
on public.scheduled_matches for update to authenticated
using (
    public.app_profile_role(auth.uid()) = 'committee'
    and public.app_profile_is_approved(auth.uid())
    and created_by = auth.uid()::text
)
with check (
    public.app_profile_role(auth.uid()) = 'committee'
    and public.app_profile_is_approved(auth.uid())
    and created_by = auth.uid()::text
);
create policy "Admins can delete matches"
on public.scheduled_matches for delete to authenticated using (public.app_is_admin());

create policy "Public can read game history"
on public.game_history for select to anon, authenticated using (true);
create policy "Dashboard users can create owned game history"
on public.game_history for insert to authenticated
with check (
    public.app_is_admin()
    or (
        public.app_profile_role(auth.uid()) = 'committee'
        and public.app_profile_is_approved(auth.uid())
        and exists (
            select 1 from public.scheduled_matches match_record
            where match_record.id = game_history.match_id
              and match_record.created_by = auth.uid()::text
        )
    )
);
create policy "Dashboard users can update owned game history"
on public.game_history for update to authenticated
using (
    public.app_is_admin()
    or exists (
        select 1 from public.scheduled_matches match_record
        where match_record.id = game_history.match_id
          and match_record.created_by = auth.uid()::text
          and public.app_profile_role(auth.uid()) = 'committee'
          and public.app_profile_is_approved(auth.uid())
    )
)
with check (
    public.app_is_admin()
    or exists (
        select 1 from public.scheduled_matches match_record
        where match_record.id = game_history.match_id
          and match_record.created_by = auth.uid()::text
          and public.app_profile_role(auth.uid()) = 'committee'
          and public.app_profile_is_approved(auth.uid())
    )
);
create policy "Admins can delete game history"
on public.game_history for delete to authenticated using (public.app_is_admin());

create policy "Public can read active announcements"
on public.announcements for select to anon, authenticated using (is_active = true);
create policy "Admins can read all announcements"
on public.announcements for select to authenticated using (public.app_is_admin());
create policy "Admins can create announcements"
on public.announcements for insert to authenticated with check (public.app_is_admin());
create policy "Admins can update announcements"
on public.announcements for update to authenticated using (public.app_is_admin()) with check (public.app_is_admin());
create policy "Admins can delete announcements"
on public.announcements for delete to authenticated using (public.app_is_admin());

create policy "Public can submit new feedback"
on public.student_feedback for insert to anon, authenticated with check (status = 'New');
create policy "Admins can read feedback"
on public.student_feedback for select to authenticated using (public.app_is_admin());
create policy "Admins can update feedback"
on public.student_feedback for update to authenticated using (public.app_is_admin()) with check (public.app_is_admin());
create policy "Admins can delete feedback"
on public.student_feedback for delete to authenticated using (public.app_is_admin());

create policy "Users can read own profile"
on public.user_profiles for select to authenticated using (id = auth.uid());
create policy "Dashboard users can read approved contacts"
on public.user_profiles for select to authenticated
using (
    public.app_is_dashboard_user()
    and lower(trim(role)) in ('admin', 'committee')
    and lower(trim(approval_status)) = 'approved'
);
create policy "Admins can read all profiles"
on public.user_profiles for select to authenticated using (public.app_is_admin());
create policy "Users can create own pending profile"
on public.user_profiles for insert to authenticated
with check (
    id = auth.uid()
    and lower(trim(role)) in ('admin', 'committee')
    and lower(trim(approval_status)) = 'pending'
);
create policy "Admins can update profiles"
on public.user_profiles for update to authenticated using (public.app_is_admin()) with check (public.app_is_admin());
create policy "Admins can delete profiles"
on public.user_profiles for delete to authenticated using (public.app_is_admin());

create policy "Participants can read own conversations"
on public.conversations for select to authenticated
using (public.app_is_dashboard_user() and auth.uid() in (created_by, receiver_id));
create policy "Users can create own conversations"
on public.conversations for insert to authenticated
with check (
    public.app_is_dashboard_user()
    and created_by = auth.uid()
    and public.app_profile_role(auth.uid()) = lower(trim(sender_role))
    and public.app_profile_role(receiver_id) = lower(trim(receiver_role))
);
create policy "Participants can update own conversations"
on public.conversations for update to authenticated
using (public.app_is_dashboard_user() and auth.uid() in (created_by, receiver_id))
with check (public.app_is_dashboard_user() and auth.uid() in (created_by, receiver_id));

create policy "Participants can read own messages"
on public.messages for select to authenticated
using (public.app_is_dashboard_user() and public.app_can_read_conversation(conversation_id));
create policy "Receivers can mark own messages read"
on public.messages for update to authenticated
using (receiver_id = auth.uid())
with check (receiver_id = auth.uid() and is_read = true);

create policy "Users can read own conversation settings"
on public.conversation_user_settings for select to authenticated
using (user_id = auth.uid() and public.app_can_read_conversation(conversation_id));

-- Storage bucket for chat photos -------------------------------------------

insert into storage.buckets (id, name, public)
values ('message-attachments', 'message-attachments', true)
on conflict (id) do update set public = excluded.public;

create policy "Public can read message attachments"
on storage.objects for select to anon, authenticated
using (bucket_id = 'message-attachments');

create policy "Dashboard users can upload own message attachments"
on storage.objects for insert to authenticated
with check (
    bucket_id = 'message-attachments'
    and public.app_is_dashboard_user()
    and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Dashboard users can delete own message attachments"
on storage.objects for delete to authenticated
using (
    bucket_id = 'message-attachments'
    and public.app_is_dashboard_user()
    and (storage.foldername(name))[1] = auth.uid()::text
);

-- Grants --------------------------------------------------------------------

grant select on public.sports, public.sports_leaderboard, public.participants,
    public.scheduled_matches, public.game_history, public.announcements
to anon, authenticated;

grant insert on public.student_feedback to anon, authenticated;
grant usage on sequence public.student_feedback_id_seq to anon;

grant select, insert, update, delete on public.sports, public.sports_leaderboard,
    public.participants, public.attendance, public.scheduled_matches,
    public.game_history, public.announcements, public.student_feedback,
    public.user_profiles
to authenticated;

grant select on public.conversation_user_settings to authenticated;
grant select, insert on public.conversations to authenticated;
grant update (unread_count_sender, unread_count_receiver) on public.conversations to authenticated;
grant select on public.messages to authenticated;
grant update (is_read) on public.messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.app_profile_role(uuid) from public;
revoke all on function public.app_profile_is_approved(uuid) from public;
revoke all on function public.app_is_admin() from public;
revoke all on function public.app_is_dashboard_user() from public;
revoke all on function public.app_can_read_conversation(uuid) from public;
revoke all on function public.app_can_send_conversation_message(uuid, uuid) from public;
revoke all on function public.save_pending_user_profile(text, text, text, text, jsonb, text) from public;
revoke all on function public.admin_set_account_approval_status(uuid, text) from public;
revoke all on function public.admin_assign_account_sport(uuid, jsonb, text) from public;
revoke all on function public.set_conversation_visibility(uuid[], boolean) from public;
revoke all on function public.send_conversation_message(uuid, uuid, text, text, text) from public;
revoke all on function public.delete_user_account(uuid) from public;

grant execute on function public.app_profile_role(uuid) to authenticated;
grant execute on function public.app_profile_is_approved(uuid) to authenticated;
grant execute on function public.app_is_admin() to authenticated;
grant execute on function public.app_is_dashboard_user() to authenticated;
grant execute on function public.app_can_read_conversation(uuid) to authenticated;
grant execute on function public.app_can_send_conversation_message(uuid, uuid) to authenticated;
grant execute on function public.save_pending_user_profile(text, text, text, text, jsonb, text) to authenticated;
grant execute on function public.admin_set_account_approval_status(uuid, text) to authenticated;
grant execute on function public.admin_assign_account_sport(uuid, jsonb, text) to authenticated;
grant execute on function public.set_conversation_visibility(uuid[], boolean) to authenticated;
grant execute on function public.send_conversation_message(uuid, uuid, text, text, text) to authenticated;
grant execute on function public.delete_user_account(uuid) to authenticated;

-- Realtime ------------------------------------------------------------------

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'sports',
        'sports_leaderboard',
        'participants',
        'attendance',
        'scheduled_matches',
        'game_history',
        'announcements',
        'student_feedback',
        'user_profiles',
        'conversations',
        'messages'
    ]
    loop
        begin
            execute format('alter publication supabase_realtime add table public.%I', table_name);
        exception
            when duplicate_object then null;
        end;
    end loop;
end
$$;

commit;
